"""Hp_rating

Revision ID: 15ed5a90cfc2
Revises: 971a470377d9
Create Date: 2025-12-15 17:43:13.006534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15ed5a90cfc2'
down_revision: Union[str, Sequence[str], None] = '971a470377d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_model'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('model', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('frame', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('winding_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('rewinding_charge', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('hp_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('model_created_by_fkey')),
    sa.PrimaryKeyConstraint('model', name=op.f('model_pkey'))
    )
    op.create_index(op.f('ix_model_model'), 'model', ['model'], unique=False)
    # ### end Alembic commands ###
