"""OW Commit

Revision ID: 27722f825dd0
Revises: beffa5fce9e3
Create Date: 2025-12-15 03:36:24.234660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27722f825dd0'
down_revision: Union[str, Sequence[str], None] = 'beffa5fce9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'user_settlement_date',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'user_settlement_date',
               existing_type=sa.DATE(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
