"""Hp_rating

Revision ID: 3ac5e4a92ffc
Revises: a6fc4b4c9d53
Create Date: 2025-12-15 23:05:07.417032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ac5e4a92ffc'
down_revision: Union[str, Sequence[str], None] = 'a6fc4b4c9d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outofwarranty_code'), table_name='outofwarranty')
    op.drop_index(op.f('ix_outofwarranty_srf_number'), table_name='outofwarranty')
    op.drop_table('outofwarranty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outofwarranty',
    sa.Column('srf_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('srf_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('head', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('problem', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('complaint_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('challan_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('challan', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('service_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('receive_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_invoice_number', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('rewinding_done', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('rewinding_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor_date2', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('vendor_cost1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor_cost2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor_bill_number', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('settlement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vendor_settlement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('repair_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vendor_paint', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('vendor_stator', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('vendor_leg', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('vendor_paint_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_stator_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_leg_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('paint_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stator_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leg_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spare1', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spare_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('godown_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('other_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gst', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('gst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('round_off', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dealer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('rpm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_challan_number', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('customer_challan_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('receive_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivered_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('collection_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('work_done', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('pc_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('service_charge_waive', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('waive_details', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('vendor_settled', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('estimate_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('final_settled', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], name=op.f('outofwarranty_code_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('outofwarranty_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], name=op.f('outofwarranty_updated_by_fkey')),
    sa.PrimaryKeyConstraint('srf_number', name=op.f('outofwarranty_pkey'))
    )
    op.create_index(op.f('ix_outofwarranty_srf_number'), 'outofwarranty', ['srf_number'], unique=False)
    op.create_index(op.f('ix_outofwarranty_code'), 'outofwarranty', ['code'], unique=False)
    # ### end Alembic commands ###
