"""OW Commit

Revision ID: 409a3962e1f2
Revises: dddaded096ad
Create Date: 2025-12-15 02:30:02.446129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '409a3962e1f2'
down_revision: Union[str, Sequence[str], None] = 'dddaded096ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outofwarranty', sa.Column('challan', sa.VARCHAR(length=1), nullable=False))
    op.drop_column('outofwarranty', 'customer_challan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outofwarranty', sa.Column('customer_challan', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_column('outofwarranty', 'challan')
    # ### end Alembic commands ###
