"""Warranty'
'


Revision ID: 421185fdfad0
Revises: 70a243479314
Create Date: 2025-12-12 09:58:31.504183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '421185fdfad0'
down_revision: Union[str, Sequence[str], None] = '70a243479314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_number',
    sa.Column('complaint_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('complaint_number')
    )
    op.create_table('model',
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('frame', sa.VARCHAR(length=10), nullable=True),
    sa.Column('winding_type', sa.VARCHAR(length=15), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('rewinding_charge', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_index(op.f('ix_model_model'), 'model', ['model'], unique=False)
    op.create_table('rewinding_rate',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('frame', sa.VARCHAR(length=10), nullable=True),
    sa.Column('winding_type', sa.VARCHAR(length=15), nullable=True),
    sa.Column('hp_rating', sa.FLOAT(), nullable=True),
    sa.Column('rewinding_charge', sa.INTEGER(), nullable=True),
    sa.Column('paint_charge', sa.INTEGER(), nullable=True),
    sa.Column('leg_charge', sa.INTEGER(), nullable=True),
    sa.Column('stator_charge', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('out_of_warranty', sa.Column('complaint_number', sa.VARCHAR(length=20), nullable=True))
    op.add_column('out_of_warranty', sa.Column('customer_challan_number', sa.VARCHAR(length=15), nullable=False))
    op.add_column('out_of_warranty', sa.Column('customer_challan_date', sa.DATE(), nullable=False))
    op.add_column('out_of_warranty', sa.Column('receive_date', sa.DATE(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('invoice_date', sa.DATE(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('vendor_paint', sa.VARCHAR(length=1), nullable=False))
    op.add_column('out_of_warranty', sa.Column('vendor_paint_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('paint_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('vendor_stator', sa.VARCHAR(length=1), nullable=False))
    op.add_column('out_of_warranty', sa.Column('vendor_stator_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('stator_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('vendor_leg', sa.VARCHAR(length=1), nullable=False))
    op.add_column('out_of_warranty', sa.Column('vendor_leg_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('leg_cost', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('vendor_cost', sa.FLOAT(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('rewinding_done', sa.CHAR(length=1), nullable=False))
    op.add_column('out_of_warranty', sa.Column('delivered_by', sa.VARCHAR(length=20), nullable=True))
    op.add_column('out_of_warranty', sa.Column('dealer_name', sa.VARCHAR(length=30), nullable=True))
    op.add_column('out_of_warranty', sa.Column('rpm', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('purchase_date', sa.DATE(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('purchase_number', sa.VARCHAR(length=15), nullable=True))
    op.alter_column('out_of_warranty', 'head',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('out_of_warranty', 'serial_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'problem',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('out_of_warranty', 'received_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('out_of_warranty', 'service_charge',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'service_charge_waive',
               existing_type=sa.CHAR(length=1),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'waive_details',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('out_of_warranty', 'invoice_number',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('out_of_warranty', 'final_status',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_column('out_of_warranty', 'estimate_date')
    op.drop_column('out_of_warranty', 'challan')
    op.drop_column('out_of_warranty', 'vendor_date1')
    op.alter_column('retail', 'details',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('warranty', sa.Column('customer_challan_number', sa.VARCHAR(length=15), nullable=False))
    op.add_column('warranty', sa.Column('customer_challan_date', sa.DATE(), nullable=False))
    op.add_column('warranty', sa.Column('received_by', sa.VARCHAR(length=30), nullable=True))
    op.add_column('warranty', sa.Column('cg_srf_number', sa.VARCHAR(length=10), nullable=True))
    op.add_column('warranty', sa.Column('work_done', sa.VARCHAR(length=50), nullable=True))
    op.add_column('warranty', sa.Column('vendor_date2', sa.DATE(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_cost1', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_cost2', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_bill_number', sa.VARCHAR(length=8), nullable=True))
    op.add_column('warranty', sa.Column('vendor_settlement_date', sa.DATE(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_settled', sa.VARCHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('vendor_paint', sa.VARCHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('vendor_paint_cost', sa.INTEGER(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_stator', sa.VARCHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('vendor_stator_cost', sa.INTEGER(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_leg', sa.VARCHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('vendor_leg_cost', sa.INTEGER(), nullable=True))
    op.add_column('warranty', sa.Column('vendor_cost', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('rewinding_done', sa.CHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('rewinding_cost', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('other_cost', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare1', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost1', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare2', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost2', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare3', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost3', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare4', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost4', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare5', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost5', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare6', sa.VARCHAR(length=20), nullable=True))
    op.add_column('warranty', sa.Column('cost6', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('spare_cost', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('godown_cost', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('discount', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('total', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('gst', sa.CHAR(length=1), nullable=False))
    op.add_column('warranty', sa.Column('gst_amount', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('final_amount', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('round_off', sa.FLOAT(), nullable=True))
    op.add_column('warranty', sa.Column('collection_date', sa.DATE(), nullable=True))
    op.add_column('warranty', sa.Column('dealer_name', sa.VARCHAR(length=30), nullable=True))
    op.add_column('warranty', sa.Column('rpm', sa.INTEGER(), nullable=True))
    op.add_column('warranty', sa.Column('pc_number', sa.INTEGER(), nullable=True))
    op.add_column('warranty', sa.Column('purchase_date', sa.DATE(), nullable=True))
    op.add_column('warranty', sa.Column('purchase_number', sa.VARCHAR(length=15), nullable=True))
    op.add_column('warranty', sa.Column('receive_amount', sa.FLOAT(), nullable=True))
    op.drop_column('warranty', 'courier')
    op.drop_column('warranty', 'challan')
    op.drop_column('warranty', 'final_remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty', sa.Column('final_remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('warranty', sa.Column('challan', sa.CHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('warranty', sa.Column('courier', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('warranty', 'receive_amount')
    op.drop_column('warranty', 'purchase_number')
    op.drop_column('warranty', 'purchase_date')
    op.drop_column('warranty', 'pc_number')
    op.drop_column('warranty', 'rpm')
    op.drop_column('warranty', 'dealer_name')
    op.drop_column('warranty', 'collection_date')
    op.drop_column('warranty', 'round_off')
    op.drop_column('warranty', 'final_amount')
    op.drop_column('warranty', 'gst_amount')
    op.drop_column('warranty', 'gst')
    op.drop_column('warranty', 'total')
    op.drop_column('warranty', 'discount')
    op.drop_column('warranty', 'godown_cost')
    op.drop_column('warranty', 'spare_cost')
    op.drop_column('warranty', 'cost6')
    op.drop_column('warranty', 'spare6')
    op.drop_column('warranty', 'cost5')
    op.drop_column('warranty', 'spare5')
    op.drop_column('warranty', 'cost4')
    op.drop_column('warranty', 'spare4')
    op.drop_column('warranty', 'cost3')
    op.drop_column('warranty', 'spare3')
    op.drop_column('warranty', 'cost2')
    op.drop_column('warranty', 'spare2')
    op.drop_column('warranty', 'cost1')
    op.drop_column('warranty', 'spare1')
    op.drop_column('warranty', 'other_cost')
    op.drop_column('warranty', 'rewinding_cost')
    op.drop_column('warranty', 'rewinding_done')
    op.drop_column('warranty', 'vendor_cost')
    op.drop_column('warranty', 'vendor_leg_cost')
    op.drop_column('warranty', 'vendor_leg')
    op.drop_column('warranty', 'vendor_stator_cost')
    op.drop_column('warranty', 'vendor_stator')
    op.drop_column('warranty', 'vendor_paint_cost')
    op.drop_column('warranty', 'vendor_paint')
    op.drop_column('warranty', 'vendor_settled')
    op.drop_column('warranty', 'vendor_settlement_date')
    op.drop_column('warranty', 'vendor_bill_number')
    op.drop_column('warranty', 'vendor_cost2')
    op.drop_column('warranty', 'vendor_cost1')
    op.drop_column('warranty', 'vendor_date2')
    op.drop_column('warranty', 'work_done')
    op.drop_column('warranty', 'cg_srf_number')
    op.drop_column('warranty', 'received_by')
    op.drop_column('warranty', 'customer_challan_date')
    op.drop_column('warranty', 'customer_challan_number')
    op.alter_column('retail', 'details',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.add_column('out_of_warranty', sa.Column('vendor_date1', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('out_of_warranty', sa.Column('challan', sa.CHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('out_of_warranty', sa.Column('estimate_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('out_of_warranty', 'final_status',
               existing_type=sa.CHAR(length=1),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'invoice_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('out_of_warranty', 'waive_details',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('out_of_warranty', 'service_charge_waive',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'service_charge',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'received_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('out_of_warranty', 'problem',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('out_of_warranty', 'serial_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('out_of_warranty', 'head',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('out_of_warranty', 'purchase_number')
    op.drop_column('out_of_warranty', 'purchase_date')
    op.drop_column('out_of_warranty', 'rpm')
    op.drop_column('out_of_warranty', 'dealer_name')
    op.drop_column('out_of_warranty', 'delivered_by')
    op.drop_column('out_of_warranty', 'rewinding_done')
    op.drop_column('out_of_warranty', 'vendor_cost')
    op.drop_column('out_of_warranty', 'leg_cost')
    op.drop_column('out_of_warranty', 'vendor_leg_cost')
    op.drop_column('out_of_warranty', 'vendor_leg')
    op.drop_column('out_of_warranty', 'stator_cost')
    op.drop_column('out_of_warranty', 'vendor_stator_cost')
    op.drop_column('out_of_warranty', 'vendor_stator')
    op.drop_column('out_of_warranty', 'paint_cost')
    op.drop_column('out_of_warranty', 'vendor_paint_cost')
    op.drop_column('out_of_warranty', 'vendor_paint')
    op.drop_column('out_of_warranty', 'invoice_date')
    op.drop_column('out_of_warranty', 'receive_date')
    op.drop_column('out_of_warranty', 'customer_challan_date')
    op.drop_column('out_of_warranty', 'customer_challan_number')
    op.drop_column('out_of_warranty', 'complaint_number')
    op.drop_table('rewinding_rate')
    op.drop_index(op.f('ix_model_model'), table_name='model')
    op.drop_table('model')
    op.drop_table('complaint_number')
    # ### end Alembic commands ###
