"""Hp_rating

Revision ID: 4c09065df3b4
Revises: 15ed5a90cfc2
Create Date: 2025-12-15 17:45:12.951419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c09065df3b4'
down_revision: Union[str, Sequence[str], None] = '15ed5a90cfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('frame', sa.VARCHAR(length=10), nullable=True),
    sa.Column('winding_type', sa.VARCHAR(length=15), nullable=True),
    sa.Column('hp_rating', sa.FLOAT(), nullable=True),
    sa.Column('rewinding_charge', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_index(op.f('ix_model_model'), 'model', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_model'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
