"""Hp_rating

Revision ID: 4ca3d5a23cd8
Revises: 6af5f2b40ce2
Create Date: 2025-12-15 21:23:19.533145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ca3d5a23cd8'
down_revision: Union[str, Sequence[str], None] = '6af5f2b40ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_charge', sa.Column('sub_division', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('service_charge', 'head')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_charge', sa.Column('head', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('service_charge', 'sub_division')
    # ### end Alembic commands ###
