"""Hp_rating

Revision ID: 6af5f2b40ce2
Revises: e45ed66c7e4f
Create Date: 2025-12-15 20:11:06.926849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6af5f2b40ce2'
down_revision: Union[str, Sequence[str], None] = 'e45ed66c7e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outofwarranty', 'user_settlement_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outofwarranty', sa.Column('user_settlement_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
