"""Hp_rating

Revision ID: 6d25cb7bf1e6
Revises: 4ca3d5a23cd8
Create Date: 2025-12-15 21:27:15.872193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d25cb7bf1e6'
down_revision: Union[str, Sequence[str], None] = '4ca3d5a23cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_charge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_charge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('division', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('service_charge', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_division', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_charge_pkey'))
    )
    # ### end Alembic commands ###
