"""Challan

Revision ID: 70a243479314
Revises: fa74a35845a9
Create Date: 2025-12-09 21:27:30.762009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70a243479314'
down_revision: Union[str, Sequence[str], None] = 'fa74a35845a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_unique',
    sa.Column('challan_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('challan_date', sa.DATE(), nullable=False),
    sa.Column('desc1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('qty1', sa.INTEGER(), nullable=False),
    sa.Column('unit1', sa.VARCHAR(length=8), nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('unit2', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('unit3', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('unit4', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('unit5', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('unit6', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc7', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty7', sa.INTEGER(), nullable=True),
    sa.Column('unit7', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc8', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty8', sa.INTEGER(), nullable=True),
    sa.Column('unit8', sa.VARCHAR(length=8), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('challan_number')
    )
    op.create_index(op.f('ix_challan_unique_challan_number'), 'challan_unique', ['challan_number'], unique=False)
    op.create_index(op.f('ix_challan_unique_code'), 'challan_unique', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challan_unique_code'), table_name='challan_unique')
    op.drop_index(op.f('ix_challan_unique_challan_number'), table_name='challan_unique')
    op.drop_table('challan_unique')
    # ### end Alembic commands ###
