"""Hp_rating

Revision ID: a6fc4b4c9d53
Revises: 6d25cb7bf1e6
Create Date: 2025-12-15 22:10:53.975234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6fc4b4c9d53'
down_revision: Union[str, Sequence[str], None] = '6d25cb7bf1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_charge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('division', sa.VARCHAR(length=10), nullable=False),
    sa.Column('sub_division', sa.VARCHAR(length=15), nullable=True),
    sa.Column('service_charge', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_charge')
    # ### end Alembic commands ###
