"""OW Commit

Revision ID: ae5765d93da4
Revises: d04d1b973dfb
Create Date: 2025-12-15 01:41:53.781074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae5765d93da4'
down_revision: Union[str, Sequence[str], None] = 'd04d1b973dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outofwarranty', sa.Column('estimate_date', sa.DATE(), nullable=True))
    op.add_column('outofwarranty', sa.Column('user_settlement_date', sa.VARCHAR(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outofwarranty', 'user_settlement_date')
    op.drop_column('outofwarranty', 'estimate_date')
    # ### end Alembic commands ###
