"""CG SRF Number

Revision ID: b13ed2f8d212
Revises: 2f4f6c0672fe
Create Date: 2025-12-22 19:37:35.508415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b13ed2f8d212'
down_revision: Union[str, Sequence[str], None] = '2f4f6c0672fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cg_srf_number',
    sa.Column('cg_srf_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('cg_srf_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cg_srf_number')
    # ### end Alembic commands ###
