"""User Commit

Revision ID: d04d1b973dfb
Revises: 90cdd2878e75
Create Date: 2025-12-15 01:08:21.054665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd04d1b973dfb'
down_revision: Union[str, Sequence[str], None] = '90cdd2878e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challan_smart', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('challan_unique', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('model', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('outofwarranty', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('outofwarranty', 'updated_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('retail', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('retail', 'updated_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('rewinding_rate', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('warranty', 'created_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('warranty', 'updated_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warranty', 'updated_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('warranty', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('rewinding_rate', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('retail', 'updated_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('retail', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('outofwarranty', 'updated_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('outofwarranty', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('model', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('challan_unique', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('challan_smart', 'created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
