"""OW Commit

Revision ID: d1e5eaad41fe
Revises: 61752c4183bb
Create Date: 2025-12-15 01:58:20.492381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1e5eaad41fe'
down_revision: Union[str, Sequence[str], None] = '61752c4183bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'service_charge_waive',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.drop_column('warranty', 'user_settlement_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty', sa.Column('user_settlement_date', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.alter_column('outofwarranty', 'service_charge_waive',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
