"""OW Commit

Revision ID: dddaded096ad
Revises: 4cbf5fb5b101
Create Date: 2025-12-15 02:06:50.706599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dddaded096ad'
down_revision: Union[str, Sequence[str], None] = '4cbf5fb5b101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'service_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('outofwarranty', 'service_charge_waive',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'service_charge_waive',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('outofwarranty', 'service_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
