"""Hp_rating

Revision ID: e45ed66c7e4f
Revises: 4c09065df3b4
Create Date: 2025-12-15 19:22:48.256334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e45ed66c7e4f'
down_revision: Union[str, Sequence[str], None] = '4c09065df3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warranty', 'final_settled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty', sa.Column('final_settled', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
