"""Hp_rating

Revision ID: ee67aa6fad4c
Revises: 27722f825dd0
Create Date: 2025-12-15 17:30:51.866625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee67aa6fad4c'
down_revision: Union[str, Sequence[str], None] = '27722f825dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('hp_rating', sa.FLOAT(), nullable=True))
    op.drop_column('model', 'rating')
    op.alter_column('outofwarranty', 'user_settlement_date',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outofwarranty', 'user_settlement_date',
               existing_type=sa.DATE(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.add_column('model', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('model', 'hp_rating')
    # ### end Alembic commands ###
