"""Rewinding Rate

Revision ID: f40db0850e1f
Revises: 6c799356721b
Create Date: 2025-12-17 12:17:52.853054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f40db0850e1f'
down_revision: Union[str, Sequence[str], None] = '6c799356721b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rewinding_rate_created_by_fkey'), 'rewinding_rate', type_='foreignkey')
    op.drop_column('rewinding_rate', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewinding_rate', sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rewinding_rate_created_by_fkey'), 'rewinding_rate', 'users', ['created_by'], ['username'])
    # ### end Alembic commands ###
