"""2nd initial

Revision ID: fa74a35845a9
Revises: 2088d27d06e6
Create Date: 2025-12-09 20:59:41.962514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa74a35845a9'
down_revision: Union[str, Sequence[str], None] = '2088d27d06e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_smart',
    sa.Column('challan_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('challan_date', sa.DATE(), nullable=False),
    sa.Column('desc1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('qty1', sa.INTEGER(), nullable=False),
    sa.Column('unit1', sa.VARCHAR(length=8), nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('unit2', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('unit3', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('unit4', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('unit5', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('unit6', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc7', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty7', sa.INTEGER(), nullable=True),
    sa.Column('unit7', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc8', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty8', sa.INTEGER(), nullable=True),
    sa.Column('unit8', sa.VARCHAR(length=8), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('challan_number')
    )
    op.create_index(op.f('ix_challan_smart_challan_number'), 'challan_smart', ['challan_number'], unique=False)
    op.create_index(op.f('ix_challan_smart_code'), 'challan_smart', ['code'], unique=False)
    op.drop_index(op.f('ix_market_code'), table_name='market')
    op.drop_index(op.f('ix_market_mcode'), table_name='market')
    op.drop_table('market')
    op.drop_index(op.f('ix_challan_challan_number'), table_name='challan')
    op.drop_index(op.f('ix_challan_code'), table_name='challan')
    op.drop_table('challan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan',
    sa.Column('challan_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('challan_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('desc1', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('qty1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit1', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit2', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc3', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit3', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc4', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit4', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc5', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty5', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit5', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc6', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty6', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit6', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc7', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty7', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit7', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('desc8', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty8', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit8', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], name=op.f('challan_code_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('challan_created_by_fkey')),
    sa.PrimaryKeyConstraint('challan_number', name=op.f('challan_pkey'))
    )
    op.create_index(op.f('ix_challan_code'), 'challan', ['code'], unique=False)
    op.create_index(op.f('ix_challan_challan_number'), 'challan', ['challan_number'], unique=False)
    op.create_table('market',
    sa.Column('mcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('receive_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('challan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('challan_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], name=op.f('market_code_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('market_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], name=op.f('market_updated_by_fkey')),
    sa.PrimaryKeyConstraint('mcode', name=op.f('market_pkey'))
    )
    op.create_index(op.f('ix_market_mcode'), 'market', ['mcode'], unique=False)
    op.create_index(op.f('ix_market_code'), 'market', ['code'], unique=False)
    op.drop_index(op.f('ix_challan_smart_code'), table_name='challan_smart')
    op.drop_index(op.f('ix_challan_smart_challan_number'), table_name='challan_smart')
    op.drop_table('challan_smart')
    # ### end Alembic commands ###
